"""
Command-line interface for converting text inputs into language learning flashcards.

This module uses the Click library to define a chained command pipeline
allowing users to specify input sources (text files, folders of text files,
or pre-processed JSONL files), apply processing steps (like sentence splitting
via a spaCy pipeline), optionally translate the content using the OpenCode Go
API, and finally output to formats like Anki (.apkg) or JSONL.

The tool is designed to be modular, with each command in the chain
acting as a step in the processing pipeline.
"""

import glob
import os
import sys
from collections.abc import Generator
from typing import Any

import alive_progress  # type: ignore
import click

from book_to_flashcards.cards_jsonl import cards_from_jsonl, cards_to_jsonl
from book_to_flashcards.Progress import Progress

from .Card import Card, card_trim_title
from .cards_to_anki import cards_to_anki
from .cards_untranslated_from_text import (
    cards_skip_first_line_if_author,
    cards_untranslated_from_file,
)
from .opencode_translator import OpenCodeGoError, OpenCodeGoTranslator
from .translate_cards import ReverseTextTranslator, translate_cards

# Global progress tracking object.
# Click's chained commands don't have a built-in way to pass state like
# progress reporters between commands in a pipeline. This global instance
# is used by input commands (like `from_folder`) to set the total number
# of steps, and by output/processing commands to update the progress bar.
__progress = Progress()


def make_progress_bar(num_steps: int):
    """Initializes and returns an alive_progress bar instance."""
    return alive_progress.alive_bar(num_steps, bar="bubbles", spinner="classic")


@click.group(chain=True)
def cli_make_flashcards():
    """Main command group for the book-to-flashcard generation pipeline."""


@cli_make_flashcards.result_callback()
def process_pipeline(processors):
    """
    Executes the chain of processor functions generated by the Click commands.

    Each processor is a generator that yields data. The output of one
    processor is fed as input to the next, forming a processing pipeline.
    A progress bar is displayed if the output is to a TTY.
    """
    iterator = None
    # Don't do progress bar if nobody can see it
    # Non tty outputs can't always handle UTF-8
    if sys.stdout.isatty():
        with make_progress_bar(__progress.num_steps) as bar:
            __progress.bar = bar
            try:
                for processor in processors:
                    iterator = processor(iterator)
            except (OSError, ValueError, TypeError, KeyError, IndexError, OpenCodeGoError) as e:
                # The pipeline steps raise these for API, parse, and file errors;
                # report the failure and let the CLI exit.
                print(e, file=sys.stderr)
    else:
        for processor in processors:
            iterator = processor(iterator)


@click.argument("inputfile", type=click.Path(readable=True, dir_okay=False))
@cli_make_flashcards.command()
def from_text(
    inputfile,
):
    """Defines the start of the pipeline, taking a single text file as input."""
    def processor(iterator):
        """Yields the input filepath."""
        yield inputfile

    return processor


@click.argument("inputpath", type=click.Path(exists=True))
@cli_make_flashcards.command()
def from_jsonl(
    inputpath,
):
    """Defines the start of the pipeline, taking the file path of a JSONL file of pre-processed cards as input."""
    def processor(iterator) -> Generator[Card, Any, Any]:
        """Yields Card objects read from the JSONL file."""
        yield from cards_from_jsonl(inputpath)

    return processor


@click.argument(
    "inputfolder",
    type=click.Path(exists=True, file_okay=False),
)
@cli_make_flashcards.command()
def from_folder(inputfolder):
    """Defines the start of the pipeline, taking a folder and finding all .txt files within it recursively."""
    files = glob.glob(inputfolder + "/**/*.txt", recursive=True)
    # It's a global variable. I don't know how to get rid of it.
    # The click framework doesn't have a way to pass progress around
    # chained commands
    # This command updates __progress.num_steps with the number of files found.
    __progress.num_steps = len(files)

    def processor(iterator) -> Generator[str, Any, Any]:
        """Yields filepaths of .txt files found in the input folder."""
        yield from files

    return processor

@cli_make_flashcards.command()
def skip_first_line_if_author():
    """Removes the first card from each book if it's assumed to be an author line.
    
    This is useful for texts where the first line is metadata (e.g., author name) 
    and not part of the content to be learned.
    """
    def processor(iterator) -> Generator[Card, Any, Any]:
        """Consumes Card objects and yields Card objects, potentially skipping the first one per book."""
        yield from cards_skip_first_line_if_author(iterator)

    return processor

@click.argument("separator", default="")
@cli_make_flashcards.command()
def remove_title_crap_after(separator:str):
    """Trims the title of each card after a specified separator string.
    
    This can be used to clean up titles, for example, if they contain unwanted
    suffixes or annotations after a certain character or string.
    The input to this processor is expected to be a generator of Card objects.
    """
    def processor(iterator: Generator[Card, Any, Any]) -> Generator[Card, Any, Any]:
        """Consumes Card objects, modifies their titles, and yields the modified Card objects."""
        for card in iterator:
            # Ensure card_obj is a Card instance before calling card_trim_title
            if isinstance(card, Card):
                yield card_trim_title(card, separator)
            else:
                # If it's not a card, yield it unchanged or handle error
                # This case should ideally not happen if pipeline is structured correctly
                raise TypeError(f"Expected Card object, got {type(card)}") 


    return processor


@click.argument(
    "outputfile", type=click.Path(dir_okay=False, writable=True), default=os.getcwd()
)
@click.option(
    "--fontsize",
    type=click.IntRange(),
    default=30,
    show_default=True,
    help="Font sized used for card text within Anki",
)
@cli_make_flashcards.command()
def to_anki(outputfile, fontsize):
    """Consumes Card objects and generates an Anki .apkg deck file.
    
    This is a terminal (final) command in the pipeline; it does not yield further data into the pipeline.
    It uses the global progress tracker to update the progress bar upon completing each file.
    """
    def processor(iterator):
        """Consumes Card objects and writes them to an Anki deck."""
        cards_to_anki(
            iterator,
            structure=True,
            fontsize=fontsize,
            ankifile=outputfile,
            on_file_complete=__progress,
        )

    return processor


@click.argument("outputpath", type=click.Path(writable=True))
@click.option("--trim", default="", help="Separator character in filename that will be used to discard unwanted trailing characters when generating jsonl filename")
@cli_make_flashcards.command()
def to_jsonl(outputpath, trim):
    """Consumes Card objects and writes them to a JSONL file.
    
    This is a terminal (final)command in the pipeline; it does not yield further data.
    It uses the global progress tracker.
    """
    def processor(iterator: Generator[Card]):
        """Consumes Card objects and writes them to a JSONL file."""
        cards_to_jsonl(iterator, outputpath, trim, __progress)

    return processor


@click.argument("pipeline", required=True)  # e.g., "en_core_web_sm", "ru_core_news_sm"
@click.option(
    "--maxfieldlen",
    type=click.IntRange(30),
    default=70,
    help="The maximum desired length of a text field (translations may be longer)",
)
@cli_make_flashcards.command()
def pipeline(pipeline, maxfieldlen):
    """Processes raw text file inputs using a spaCy NLP pipeline to split them into Card objects.
    
    This command consumes filepaths (strings), processes each file using the
    specified spaCy pipeline and maxfieldlen, and yields Card objects.
    """
    def processor(iterator: Generator[str]) -> Generator[Card]:
        """Consumes filepaths, processes files to Cards, and yields them."""
        for filename in iterator:
            yield from cards_untranslated_from_file(
                inputfile=filename, pipeline=pipeline, maxfieldlen=maxfieldlen
            )

    return processor


@click.option(
    "--lang",
    default="English",
    show_default=True,
    help="Language to translate into, e.g. English, Spanish, French",
)
@click.option(
    "--model",
    default="deepseek-v4-flash",
    show_default=True,
    help="Model to use for translations (served by the OpenCode Go provider, e.g. deepseek-v4-pro)",
)
@cli_make_flashcards.command()
def translate(lang, model):
    """Translates the 'front' field of each Card object using the OpenCode Go API.
    
    This command consumes Card objects, adds translations to their 'back' field, 
    and yields the translated Card objects.
    The API key is taken from the OPENCODE_API_KEY environment variable or from
    opencode's auth file (see `opencode auth`). Cards are translated in batches,
    in the context of the surrounding text of their book.
    """
    def processor(iterator) -> Generator[Card]:
        """Consumes Card objects, adds translations, and yields them."""
        translator = OpenCodeGoTranslator(model=model)
        yield from translate_cards(iterator, translator, lang)

    return processor


@cli_make_flashcards.command()
def dummy_translate():
    """'Translates' cards by reversing their front text. 
    
    Useful for testing the pipeline without making actual API calls to the
    translation service.
    """
    def processor(iterator) -> Generator[Card]:
        """Consumes Card objects, adds 'reversed' translations, and yields them."""
        translator = ReverseTextTranslator()
        yield from translate_cards(iterator, translator, "dummy")

    return processor
